site_name: Portfolio

theme:
  name: material
  language: en
  # logo: images\Logo.png
  # favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.top
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About: about.md
  - Resume:
      - Professional Resume: resume/resume.md
      - Skills & Expertise: resume/skills.md
  - Portfolio:
      - Overview: portfolio/portfolio.md
      - Projects: portfolio/projects.md
  - Blog:
      - Blogs: blog/blogs.md
  - Contact: contact.md

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - meta
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Maimoon-github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/maimoon-moon-amin/
    - icon: fontawesome/solid/envelope
      link: https://mail.google.com/mail/u/0/#inbox?compose=new
